apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-instantiate-template
spec:
  params:
  - name: TEMPLATE
    type: string
  - name: PARAMS
    type: string
  steps:
    - name: instantiate-template
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli
      script: |
        oc process $(params.TEMPLATE) $(params.PARAMS) | oc create -f -
