apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: factory-to-central
  namespace: manuela-stormshift-messaging
spec:
  version: 3.1.0
  replicas: 1
  connectCluster: manuela-data-lake
  clusters:
    - alias: manuela-data-lake
      bootstrapServers: 'prod-kafka-cluster-kafka-2-manuela-data-lake.{{ .Values.global.hubClusterDomain }}:443'
    - alias: manuela-factory-kafka
      bootstrapServers: 'factory-kafka-cluster-kafka-bootstrap.manuela-stormshift-messaging.svc:9092'
      config:
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1  
  mirrors:
    - sourceCluster: manuela-factory-kafka
      targetCluster: manuela-data-lake
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: 'false'
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      topicsPattern: .*
      groupsPattern: .*
