main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: revoman
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: therevoman
    username: therevoman
    email: nrevo@redhat.com
    dev_revision: edge-demo

  s3:
    bucket:
      name: nrevo-edge-demo
      region: us-east-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
