apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
  namespace: manuela-tst-all
spec:
  channel: stable
  installPlanApproval: {{ .Values.installPlanApproval }}
  name: seldon-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
    #startingCSV: seldon-operator.{{ .Values.subscriptions.version.seldon }}
