global:
  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

messaging:
  vibrationAlert: true
  vibrationAnomaly: true 
  nodeTlsReject: 0

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: false

mqtt:
  broker:
    uri: "tcp://broker-amq-mqtt-all-0-svc:61616"
    clientId: "MQTT2KafkaRoute"
    topic:
      temperature: "iot-sensor/sw/temperature"
      vibration: "iot-sensor/sw/vibration"

kafka:
  broker:
    uri: "dev-kafka-cluster-kafka-bootstrap.manuela-tst-all.svc:9092"
    topic:
      temperature: "iot-sensor-sw-temperature"
      vibration: "iot-sensor-sw-vibration"
    
subscriptions:
  version:
    installPlanApproval: Automatic
    seldon: v1.13.1
